name: some
version: "2.0.0"
description: "Some / Maybe / Option / Result / Nullable, like Haskel Maybe, Can avoid semantic confusion caused by returning null when returning a value"
homepage: "https://github.com/MeowType/MaybeDart"
repository: "https://github.com/MeowType/MaybeDart"
issue_tracker: "https://github.com/MeowType/MaybeDart/issues"
environment:
  sdk: ">=2.14.0 <3.0.0"
dev_dependencies:
  test: ^1.6.5
