name: some
version: '1.2.2'
description: 'Some / Maybe / Option / Result / Nullable, like Haskel Maybe, Can avoid semantic confusion caused by returning null when returning a value'
authors:
- 'MeowType <aditrc@outlook.com>'
- '2A5F <U2A5F@outlook.com>'
homepage: 'https://github.com/MeowType/MaybeDart'
repository: 'https://github.com/MeowType/MaybeDart'
issue_tracker: 'https://github.com/MeowType/MaybeDart/issues'
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.6.5